import React, { useMemo } from 'react';
import { Printer, Calendar, CheckCircle, AlertCircle, Clock, PieChart, BarChart } from 'lucide-react';

const ReportsView = ({ tasks, project, currentUser }) => {
    // Calculate Statistics
    const stats = useMemo(() => {
        const total = tasks.length;
        const done = tasks.filter(t => t.status === 'DONE').length;
        const inProgress = tasks.filter(t => t.status === 'IN PROGRESS').length;
        const todo = tasks.filter(t => t.status === 'TO DO').length;
        const completionRate = total > 0 ? Math.round((done / total) * 100) : 0;

        const now = new Date();
        const overdue = tasks.filter(t => {
            if (t.status === 'DONE' || !t.dueDate) return false;
            return new Date(t.dueDate) < now;
        }).length;

        // Priority breakdown
        const priorities = { 'Highest': 0, 'High': 0, 'Medium': 0, 'Low': 0, 'Lowest': 0 };
        tasks.forEach(t => {
            if (priorities[t.priority] !== undefined) priorities[t.priority]++;
            else priorities['Medium']++; // Default
        });

        // Assignee breakdown
        const assignees = {};
        tasks.forEach(t => {
            const name = t.assignee || 'Unassigned';
            assignees[name] = (assignees[name] || 0) + 1;
        });

        return { total, done, inProgress, todo, completionRate, overdue, priorities, assignees };
    }, [tasks]);

    const handlePrint = () => {
        window.print();
    };

    const StatusBar = ({ label, count, color, total }) => {
        const width = total > 0 ? (count / total) * 100 : 0;
        return (
            <div className="mb-4">
                <div className="flex justify-between text-sm mb-1">
                    <span className="font-medium text-gray-700 dark:text-gray-300">{label}</span>
                    <span className="text-gray-500">{count} ({Math.round(width)}%)</span>
                </div>
                <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2.5">
                    <div className={`h-2.5 rounded-full ${color}`} style={{ width: `${width}%` }}></div>
                </div>
            </div>
        );
    };

    return (
        <div className="flex-grow overflow-y-auto p-4 md:p-8 bg-white dark:bg-[#1e2124] text-text-light dark:text-text-dark min-h-full">

            {/* Print Friendly Header - Only visible when printing */}
            <div className="hidden print:block mb-8 border-b-2 border-gray-300 pb-4">
                <h1 className="text-3xl font-bold text-gray-900">{project?.name || 'Project'} Report</h1>
                <div className="flex justify-between mt-4 text-sm text-gray-600">
                    <span>Generated on: {new Date().toLocaleString()}</span>
                    <span>Generated by: {currentUser?.name || 'Unknown User'}</span>
                </div>
            </div>

            {/* Screen Header - Hidden when printing */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 print:hidden gap-4">
                <div>
                    <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Project Report</h2>
                    <p className="text-gray-500 dark:text-gray-400 mt-1">
                        Comprehensive overview for <span className="font-semibold text-primary">{project?.name}</span>
                    </p>
                </div>
                <button
                    onClick={handlePrint}
                    className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md transition-colors shadow-sm"
                >
                    <Printer size={18} />
                    <span>Print Report</span>
                </button>
            </div>

            {/* Executive Summary Cards */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
                <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg border border-blue-100 dark:border-blue-900/30">
                    <div className="flex items-center gap-2 text-blue-600 dark:text-blue-400 mb-2">
                        <CheckCircle size={20} />
                        <span className="font-semibold text-sm">Completion Rate</span>
                    </div>
                    <span className="text-3xl font-bold text-gray-900 dark:text-white">{stats.completionRate}%</span>
                    <p className="text-xs text-gray-500 mt-1">{stats.done} tasks completed</p>
                </div>

                <div className="bg-purple-50 dark:bg-purple-900/20 p-4 rounded-lg border border-purple-100 dark:border-purple-900/30">
                    <div className="flex items-center gap-2 text-purple-600 dark:text-purple-400 mb-2">
                        <PieChart size={20} />
                        <span className="font-semibold text-sm">Total Tasks</span>
                    </div>
                    <span className="text-3xl font-bold text-gray-900 dark:text-white">{stats.total}</span>
                    <p className="text-xs text-gray-500 mt-1">Across all statuses</p>
                </div>

                <div className="bg-yellow-50 dark:bg-yellow-900/20 p-4 rounded-lg border border-yellow-100 dark:border-yellow-900/30">
                    <div className="flex items-center gap-2 text-yellow-600 dark:text-yellow-400 mb-2">
                        <Clock size={20} />
                        <span className="font-semibold text-sm">In Progress</span>
                    </div>
                    <span className="text-3xl font-bold text-gray-900 dark:text-white">{stats.inProgress}</span>
                    <p className="text-xs text-gray-500 mt-1">Active tasks</p>
                </div>

                <div className="bg-red-50 dark:bg-red-900/20 p-4 rounded-lg border border-red-100 dark:border-red-900/30">
                    <div className="flex items-center gap-2 text-red-600 dark:text-red-400 mb-2">
                        <AlertCircle size={20} />
                        <span className="font-semibold text-sm">Overdue</span>
                    </div>
                    <span className="text-3xl font-bold text-gray-900 dark:text-white">{stats.overdue}</span>
                    <p className="text-xs text-gray-500 mt-1">Past due date</p>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8 print:grid-cols-2">
                {/* Status Breakdown */}
                <div className="bg-gray-50 dark:bg-card-dark p-6 rounded-lg border border-gray-100 dark:border-border-dark">
                    <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
                        <BarChart size={18} className="text-gray-500" />
                        Status Breakdown
                    </h3>
                    <StatusBar label="To Do" count={stats.todo} total={stats.total} color="bg-gray-500" />
                    <StatusBar label="In Progress" count={stats.inProgress} total={stats.total} color="bg-blue-500" />
                    <StatusBar label="Done" count={stats.done} total={stats.total} color="bg-green-500" />
                </div>

                {/* Priority Distribution */}
                <div className="bg-gray-50 dark:bg-card-dark p-6 rounded-lg border border-gray-100 dark:border-border-dark">
                    <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
                        <AlertCircle size={18} className="text-gray-500" />
                        Priority Distribution
                    </h3>
                    <div className="space-y-3">
                        {Object.entries(stats.priorities).map(([priority, count]) => {
                            if (count === 0) return null;
                            const colors = {
                                'Highest': 'bg-red-600',
                                'High': 'bg-orange-500',
                                'Medium': 'bg-yellow-500',
                                'Low': 'bg-blue-400',
                                'Lowest': 'bg-blue-300'
                            };
                            return (
                                <div key={priority} className="flex items-center gap-3">
                                    <div className={`w-3 h-3 rounded-full ${colors[priority]}`}></div>
                                    <div className="flex-grow flex justify-between text-sm">
                                        <span className="text-gray-700 dark:text-gray-300">{priority}</span>
                                        <span className="font-semibold text-gray-900 dark:text-white">{count}</span>
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </div>
            </div>

            {/* Task List Table */}
            <div className="border border-gray-200 dark:border-border-dark rounded-lg overflow-hidden bg-white dark:bg-card-dark">
                <div className="bg-gray-50 dark:bg-[#2b3036] px-6 py-4 border-b border-gray-200 dark:border-border-dark">
                    <h3 className="text-lg font-semibold">Detailed Task List</h3>
                </div>
                <div className="overflow-x-auto">
                    <table className="w-full text-sm text-left">
                        <thead className="bg-gray-50 dark:bg-[#2b3036] text-gray-500 font-medium border-b border-gray-200 dark:border-border-dark">
                            <tr>
                                <th className="px-6 py-3 w-24">Key</th>
                                <th className="px-6 py-3">Summary</th>
                                <th className="px-6 py-3 w-32">Status</th>
                                <th className="px-6 py-3 w-32">Priority</th>
                                <th className="px-6 py-3 w-40">Assignee</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-100 dark:divide-border-dark">
                            {tasks.length === 0 ? (
                                <tr>
                                    <td colSpan="5" className="px-6 py-8 text-center text-gray-500">No tasks found.</td>
                                </tr>
                            ) : (
                                tasks.slice(0, 50).map(task => (
                                    <tr key={task.id} className="hover:bg-gray-50 dark:hover:bg-[#2c313a]">
                                        <td className="px-6 py-3 text-blue-600 font-medium">{task.key}</td>
                                        <td className="px-6 py-3 text-gray-800 dark:text-gray-200">{task.title}</td>
                                        <td className="px-6 py-3">
                                            <span className={`px-2 py-1 rounded text-xs font-bold uppercase
                                                ${task.status === 'DONE' ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400' :
                                                    task.status === 'IN PROGRESS' ? 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400' :
                                                        'bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-200'}`}>
                                                {task.status}
                                            </span>
                                        </td>
                                        <td className="px-6 py-3 text-gray-600 dark:text-gray-300">{task.priority}</td>
                                        <td className="px-6 py-3">
                                            <div className="flex items-center gap-2">
                                                <div className="w-6 h-6 rounded-full bg-indigo-100 text-indigo-600 flex items-center justify-center text-xs font-bold">
                                                    {task.assignee ? task.assignee.charAt(0) : '?'}
                                                </div>
                                                <span className="truncate max-w-[100px]">{task.assignee}</span>
                                            </div>
                                        </td>
                                    </tr>
                                ))
                            )}
                            {tasks.length > 50 && (
                                <tr>
                                    <td colSpan="5" className="px-6 py-3 text-center text-gray-500 italic">
                                        ... and {tasks.length - 50} more tasks.
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            <div className="mt-8 text-center text-gray-400 text-xs print:block hidden">
                Report generated by JIRA Clone App
            </div>
        </div>
    );
};

export default ReportsView;
